### ISSUE TITLE
password reset:error page--MethodNotAllowedHttpException in RouteCollection.php line 219:

### ISSUE THREAD

**Issue by JinYucen** [PrestonEn/BarbaricWaffle#29]
Password reset
go to the error page --MethodNotAllowedHttpException in RouteCollection.php line 219:
when submit with both registered email
ie: submit with the input:  user name: 123@123
                                         email:123@123
with e-mail 123@123 just registered and signed up

**Comment by JinYucen** [comment]
it seems not working whatever the 2 inputs entered.

**Comment by Andesha** [comment]
pw reset now works
